/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RecipeNow;

import java.awt.event.WindowEvent;
import java.sql.SQLException;

/**
 *
 * @author Son
 */
public class MainMenu extends javax.swing.JFrame{

    /**
     * Creates new form MainMenu
     */
    
    private int userid;
    private String username;
    private DatabaseHelper db;
    
    public MainMenu(int userid, String username, DatabaseHelper db) {
        
        this.userid = userid;
        this.username = username;
        this.db = db;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenu_printIngList = new javax.swing.JButton();
        mainMenu_addIng = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Main Menu");

        mainMenu_printIngList.setText("Print Ingredient List");
        mainMenu_printIngList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMenu_printIngListMouseClicked(evt);
            }
        });

        mainMenu_addIng.setText("Ingredient Menu");
        mainMenu_addIng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMenu_addIngMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(487, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mainMenu_printIngList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainMenu_addIng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(mainMenu_printIngList)
                .addGap(18, 18, 18)
                .addComponent(mainMenu_addIng)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenu_printIngListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenu_printIngListMouseClicked
        
        try {
            db.printIngredientTable();
        } catch (SQLException ex) {
            System.out.println("SQL Exception: " + ex.getMessage());
        }
       
    }//GEN-LAST:event_mainMenu_printIngListMouseClicked

    private void mainMenu_addIngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenu_addIngMouseClicked
        
        // Open new ingredient window
        IngredientMenu newIngredientMenu = new IngredientMenu(this.db);
        
        newIngredientMenu.setVisible(true);
        
        
    }//GEN-LAST:event_mainMenu_addIngMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mainMenu_addIng;
    private javax.swing.JButton mainMenu_printIngList;
    // End of variables declaration//GEN-END:variables
    @Override
    protected void processWindowEvent(final WindowEvent e) {
        super.processWindowEvent(e);

        if (e.getID() == WindowEvent.WINDOW_CLOSING) {
            RecipeNow.app.start = new NewUserCntl();
            dispose();
        }
    }
}
