/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RecipeNow;

import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author Youngmin
 */
public class NewIngredient extends javax.swing.JFrame implements GuiHelper {

    /**
     * Creates new form NewIngredient
     */
    
    DatabaseHelper db;
    
    public NewIngredient(DatabaseHelper db)  {
        initComponents();
        this.db = db;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newIng_addIng = new javax.swing.JButton();
        newIng_Exit = new javax.swing.JButton();
        newIng_ingName = new javax.swing.JTextField();
        newIng_ingCal = new javax.swing.JTextField();
        newIng_isDairy = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Ingredient");

        newIng_addIng.setText("Add");
        newIng_addIng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newIng_addIngMouseClicked(evt);
            }
        });

        newIng_Exit.setText("Cancel");
        newIng_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newIng_ExitMouseClicked(evt);
            }
        });

        newIng_ingName.setText("Enter Ingredient Name");
        newIng_ingName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newIng_ingNameMouseClicked(evt);
            }
        });

        newIng_ingCal.setText("Enter Ingredient Calorie");
        newIng_ingCal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newIng_ingCalMouseClicked(evt);
            }
        });

        newIng_isDairy.setText("Dairy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newIng_ingCal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(newIng_ingName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newIng_isDairy)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(newIng_addIng, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(newIng_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newIng_ingName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newIng_ingCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newIng_isDairy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newIng_addIng)
                    .addComponent(newIng_Exit))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void newIng_ingNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newIng_ingNameMouseClicked
        // Empty text field when user clicks 
        if(newIng_ingName.getText().equals("Enter Ingredient Name") || newIng_ingName.getText().isEmpty()) {
            newIng_ingName.setText(""); 
        }
    }//GEN-LAST:event_newIng_ingNameMouseClicked

    private void newIng_ingCalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newIng_ingCalMouseClicked
        // Empty text field when user clicks 
        if(newIng_ingCal.getText().equals("Enter Ingredient Calorie") || newIng_ingCal.getText().isEmpty()) {
            newIng_ingCal.setText(""); 
        }  
    }//GEN-LAST:event_newIng_ingCalMouseClicked

    private void newIng_addIngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newIng_addIngMouseClicked
        
        // Check if name and calorie text fields are filled 
        boolean checkNull = checkNull();
        boolean hasDuplicate;
        String dairy = newIng_isDairy.isSelected() == true ? "YES" : "NO";
        
        if(!checkNull) {
            String ingredName = newIng_ingName.getText();
            int ingredCal;
            try {
            ingredCal = Integer.parseInt(newIng_ingCal.getText());
            } catch (NumberFormatException ex) {
                System.out.println("NumberFormatException: " + ex.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Please only enter numeric values", "Error", HEIGHT);
                resetComponent();
                
                // exit function
                return;
            }
            try {
                hasDuplicate = this.db.ingredientInsertIntoTable(ingredName, ingredCal, dairy);
                if(hasDuplicate) {
                    System.out.println("Add Ingredient Failed");
                    JOptionPane.showMessageDialog(rootPane, "The ingredient is already in the database or Server Connection has failed", "Error", HEIGHT);
                } else {
                    System.out.println("Add Ingredient Success " + " Ingredient Name: " + newIng_ingName.getText() + " Ingredient Calroie " + newIng_ingName.getText());
                    JOptionPane.showMessageDialog(rootPane, "Registration Success", "Success", HEIGHT);
                }
            } catch (SQLException ex) {
                System.out.println("SQL Exception: " + ex.getMessage());
            } 
        }
        resetComponent();
        
    }//GEN-LAST:event_newIng_addIngMouseClicked

    private void newIng_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newIng_ExitMouseClicked
        closeFrame();
    }//GEN-LAST:event_newIng_ExitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton newIng_Exit;
    private javax.swing.JButton newIng_addIng;
    private javax.swing.JTextField newIng_ingCal;
    private javax.swing.JTextField newIng_ingName;
    private javax.swing.JCheckBox newIng_isDairy;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean checkNull() {
       // Check if the two textfields are null or default    
        return newIng_ingName.getText().equals("") || newIng_ingCal.getText().equals("");
    }

    @Override
    public void resetComponent() {
        newIng_ingName.setText("Enter Ingredient Name");
        newIng_ingCal.setText("Enter Ingredient Calorie");
        
    }

    @Override
    public void closeFrame() {
        // Close current frame
        NewIngredient.this.dispose();
    }
}
